### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by aehlke** [99-Knots/PrettyYomitanCards#2]
Nice work! Is there an open source license on it?

**Comment by 99-Knots** [comment]
Thank you! I haven't decided on what exact license I want yet. Are you asking for a specific reason?

**Comment by aehlke** [comment]
@99-Knots I'd like to use your pitch accent charts for my app, Manabi Reader

**Comment by 99-Knots** [comment]
Those charts are not generated by me. They are provided by Yomitan based on the data of a pitch accent dictionary.
